### ISSUE TITLE
Load all components within a folder

### ISSUE THREAD

**Issue by davidsneighbour** [FranckFreiburger/http-vue-loader#104]
I have quite a lot of components in various folders. Is it possible to somehow load all files in a folder and map them to their filename as component name? Is that a useful improvement?

Something along the lines of 

```
  components: {
    '*': httpVueLoader('/components/*.vue'),
  },
```

**Comment by pal-software** [comment]
I think it's task not for httpVueLoader, because client javascript httpVueLoader have not access to server or local filesystem & can't enumerate files.

If your files with components placed on the some web-server (with php for example), then you can write server-side function & make list of components dynamically.

**Comment by FranckFreiburger** [comment]
This feature can be done in userland

**Comment by davidsneighbour** [comment]
Can you go into depth on that? I don't have an idea what you mean by "userland" in connection with a Vue app.
