### ISSUE TITLE
Docs Request: add documentation for loading .vue file via CDN

### ISSUE THREAD

**Issue by DrSensor** [FranckFreiburger/http-vue-loader#30]
Hello and thank you for this loader. I have a use case where I need to load .vue file at runtime because my application have requirement for plugin feature. I'm thinking of using this loader for that. Can this loader do that via CDN and/or local files? Also can this loader load minifed vue component (outputted as .js) at runtime?

**Comment by FranckFreiburger** [comment]
`http-vue-loader` load `.vue` files through XMLHttpRequest (by default), then you can load components that are available on a CDN.
Loading local files depend on the CORS policy of your browser, on chrome, you will get the following error: `Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`
Since a "minifed vue component" is a vue components, `http-vue-loader` should be able to load them.
