### ISSUE TITLE
Load .vue component  file from within other .vue component at runtime

### ISSUE THREAD

**Issue by GeorgeGkinis** [FranckFreiburger/http-vue-loader#34]
Hello,

In the examples I see how I can load and register .vue component files in my index.html file.

I am wondering if i can use this functionality from within an existing .vue file.

example : 

```
<template>
    <dynamicComponent/>
</template>

<script>
    export default {
        name: "example-lazy-load",
      components: {
          'dynamicComponent' : httpVueLoader('https://url/component.vue')
      }
    }
</script>

<style scoped>

</style>
```

Is this possible?

If I try this I get :
```
  vue.esm.js?65d7:591 [Vue warn]: Failed to resolve async component: function () {

			return new Component(name).load(url)
			.then(function(component) {

				return component.normalize();
			})
			.then(function(component) {

				return component.compile();
			})
			.then(function(component) {

				var exports = component.script !== null ? component.script.module.exports : {};

				if ( component.template !== null )
					exports.template = component.template.getContent();

				if ( exports.name === undefined )
					if ( component.name !== undefined )
						exports.name = component.name;

				exports._baseURI = component.baseURI;

				return exports;
			});
		}
Reason: SyntaxError: Unexpected token export
```
The component.vue file is accessible and I can see the contents if I visit ***http://url/component.vue*** with my browser.
 
I do include  `<script src="https://unpkg.com/http-vue-loader"></script>` in my index.html file.

Thanks,

George.

**Comment by GeorgeGkinis** [comment]
For completeness also the contents of dynamicComponent : 
```
<template>
    <dynamicComponent/>
</template>

<script>
    export default {
        name: "example-lazy-load",
      components: {
          'dynamicComponent' : httpVueLoader('https://url/component.vue')
      }
    }
</script>

<style scoped>

</style>
```

**Comment by GeorgeGkinis** [comment]
It seems to be an ES6/ES5 error: 
```
<template>

<p>Hello from {{str}}</p>
</template>

<script>
module.exports = {
  data: function() {
    return {
      str: 'test'
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>
```
I changed **export default {** to **module.exports = {** and everything works!!

Thank you for your library 👍 

George.

**Comment by gabalicious** [comment]
Care to comment why this is closed.  I'm having a similar issue.

**Comment by btsimonh** [comment]
I have to write this somewhere, and this seems to be an appropriate place, even though the issue is closed.
I've been working at this all day. I was trying to add a second child component to my dynamically loaded .vue component.

source snippet:
```
    <routines @mounted="mountedRoutines"/>
    <room v-bind:test="'hello'" @mounted="mountedRoom"/>
  </div>
</template>

<script>

module.exports = {
  components: {
    room: httpVueLoader('./room.vue', 'room'),
    routines: httpVueLoader('./routines.vue', 'routines'),
  },
````

Does NOT work.  It reliably loads one of the components, but the other is fairly silently ignored.
But...  if you use:
```
    <routines @mounted="mountedRoutines"></routines>
    <room v-bind:test="'hello'" @mounted="mountedRoom"></room>
```
Then magically it works...
So, if trying to add more than one component, make sure you use the fill <></> syntax.
@FranckFreiburger - let me know if you want me to open this as a full issue.  I'm happy that it works for me at the moment, if was just frustrating that I did not try the full syntax earlier today :).  & thanks for a nice loader - which I've used in production for 2 years - because I specifically want to allow people to write components and dynamically load them.
